- name: Install Docker into Debian like system
  block:
  - name: install packages
    apt:
      name:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg2
        - software-properties-common
      state: present
      update_cache: yes
      cache_valid_time: 3600

  - name: install repo key
    apt_key:
      url: https://download.docker.com/linux/{{ ansible_distribution 4 | lower }}/gpg
      state: present

  - apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
      state: present

  - name: install docker
    apt:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
      update_cache: yes
      cache_valid_time: 3600
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install Docker into RedHat like system
  block:
    - name: Add Docker repo
      copy:
        src: docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo

    - name: Enable Docker Edge repo
      ini_file:
        dest: /etc/yum.repos.d/docker-ce.repo
        section: 'docker-ce-edge'
        option: enabled
        value: 0

    - name: Install Docker
      yum:
        name: docker-ce
        state: latest
        update_cache: yes
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: put docker config
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
  notify: restart docker daemon

- name: Check for Python
  raw: test -e /usr/bin/python
  changed_when: false
  failed_when: false
  register: check_python

- name: set timezone to Europe/Moscow
  timezone:
   name: Europe/Moscow

- name: Install NTP
  apt: name=ntp update_cache=yes

- name: Install the NTP daemon to synchronize the clocks to ms.
  apt: name=ntp

- name: Make sure ntp is started, and is enabled on restart.
  service: name=ntp state=started enabled=yes

- name: autofs
  apt: name=autofs state=latest

- name: Отключаем AutoFS
  ansible.builtin.shell: sudo systemctl disable autofs

- name: add GRUB_CMDLINE_LINUX="ipv6.disable=1
  lineinfile:
    path: /etc/default/grub
    line: 'GRUB_CMDLINE_LINUX="ipv6.disable=1"'
    insertafter: '^GRUB_CMDLINE_LINUX=*'

- name: add GRUB_CMDLINE_LINUX="audit=1"
  lineinfile:
    path: /etc/default/grub
    line: 'GRUB_CMDLINE_LINUX="audit=1"'
    insertafter: '^GRUB_CMDLINE_LINUX="ipv6*'

- name: add GRUB_CMDLINE_LINUX="audit_backlog_limit=8192"
  lineinfile:
    path: /etc/default/grub
    line: 'GRUB_CMDLINE_LINUX="audit_backlog_limit=8192"'
    insertafter: '^GRUB_CMDLINE_LINUX="audit=1*'
